### PR TITLE
Create AUR package

### PR DESCRIPTION
**Pull request by jneidel**
I created an AUR package: https://aur.archlinux.org/packages/shell-velocity-git

### CODE REVIEW

**Comment by saccarosium** [comment]
I've look the AUR package, and looks mostly good. The only issue I have is that you have made the default picker Dmenu when fzf is the default.

**Comment by jneidel** [comment]
> you have made the default picker Dmenu

Where did you get that?

optdepends are only messages shown to inform the user of interactions with other packages.

**Comment by saccarosium** [comment]
Sorry my bad, I've miss read the page.

Also one question this will always get the latest from github I'm getting this right. Currently I don't have a way to track the version of the script should I implemet that?

**Comment by jneidel** [comment]
You don't have to do versions, not for my sake.

This line creates a version nr from via git:
```
printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
```

The `-git` post fix in the pkg name means, that it pull the latest from the git repo (which is totally fine and what ppl will expect).

**Comment by saccarosium** [comment]
> ou don't have to do versions, not for my sake.
> 
> This line creates a version nr from via git:
> 
> ```
> printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
> ```
> 
> The `-git` post fix in the pkg name means, that it pull the latest from the git repo (which is totally fine and what ppl will expect).

Thanks for the clarification! Merged.

**Pull request merged**
